name: Presubmit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md"]'
          do_not_skip: '["pull_request"]'
  run_tests_gcc:
    strategy:
      matrix:
        deps: ["thapi@develop+clang-parser"]
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3.13
      if: ${{ inputs.debug_enabled }}
    - name: Checkout Spack
      uses: actions/checkout@v4
      with:
        repository: spack/spack
        ref: releases/latest
        path: external/spack
    - name: Activate, Add Spack
      run: |
        # install llvm+clang
        sudo apt-get install libllvm18 llvm-18 llvm-18-dev
        sudo apt-get install libclang-18-dev
        # find the prefix where libclang is installed
        llvm_prefix=`llvm-config-18 --prefix`

        # initialize spack
        . external/spack/share/spack/setup-env.sh
        # add thapi
        spack repo add ./
        # find compilers
        spack compiler find
        # find external packages known to spack (avoid bzip2, xz and llvm
        # discovery due to errors).
        spack external find --all --exclude bzip2 --exclude xz --exclude llvm

        # point spack to llvm+clang installed through apt-get
        echo "  llvm:"                      >> ~/.spack/packages.yaml
        echo "    buildable: false"         >> ~/.spack/packages.yaml
        echo "    externals:"               >> ~/.spack/packages.yaml
        echo "    - spec: llvm@18+clang"    >> ~/.spack/packages.yaml
        echo "      prefix: ${llvm_prefix}" >> ~/.spack/packages.yaml

        spack -d spec ${{ matrix.deps }}
        spack install --show-log-on-error --fail-fast ${{ matrix.deps }}
    - name: Block to allow inspecting failures
      run: sleep 30m
      if: ${{ failure() && inputs.debug_enabled }}
